[package]
name = "switzerland"
version = "0.1.0"
edition = "2024"

[dependencies]
uniffi = { version = "0.29", features = ["cli"] }

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[profile.release]
strip = true
opt-level = "z" 
lto = true
codegen-units = 1
panic = "abort"